[package]
name = "photon-slam"
version = "0.1.0"
edition = "2024"

[dependencies]
vulkano = "0.35.2"
winit = { version = "0.30.13", features = ["android-native-activity"] }
image = "0.25"
log = "0.4"
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
bytemuck = "1.25.0"
anyhow = "1.0.103"
thiserror = "2.0.18"
v4l = "0.14.0"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
android-activity = { version = "0.6", features = ["native-activity"] }

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.android]
# The minimum API level your app will run on (e.g., 21 for Android 5.0)
min_sdk_version = 21

# The target API level (Set this to the latest, e.g., 35 or 36)
target_sdk_version = 30

# Optional: Specify the build tools version if auto-detection fails
build_tools_version = "35.0.0"
